<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Description>KurrentDB provider for EventSourcingDotNet</Description>
        <RootNamespace>EventSourcingDotNet.KurrentDB</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\EventSourcingDotNet\EventSourcingDotNet.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="DynamicProxyGenAssembly2"/>
        <InternalsVisibleTo Include="EventSourcingDotNet.KurrentDB.SourceGeneratorTests"/>
    </ItemGroup>
  
    <ItemGroup>
        <PackageReference Include="KurrentDB.Client" />
        <PackageReference Include="System.Reactive"/>
    </ItemGroup>
</Project>
