name: .NET

on:
  push:
    branches: [ "main" ]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx"
      - name: Test Results
        uses: dorny/test-reporter@v1
        id: test-report
        if: success() || failure()
        with: 
          name: Unit Tests
          path: "**/TestResults/test-results.trx"
          reporter: dotnet-trx
          list-tests: "failed"
          
  push:
    if: github.repository == 'woodworm83/EventSourcingDotNet'
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Pack nuget packages
        run: dotnet pack --no-restore -c Release
      - name: Push nuget package
        run: dotnet nuget push -s nuget.org --api-key ${{ secrets.nugetApiKey }} --skip-duplicate src/**/*.nupkg
        